language: scala

sudo: required

services:
  - docker

scala:
  - "2.12.7"
  - "2.11.12"

jdk:
  - oraclejdk8

# default script for jobs, that do not have any specified
script:
  - ${PRE_CMD:=return 0} # do nothing if not set
  - sbt -jvm-opts .jvmopts-travis "$CMD"

jobs:
  include:
    - stage: whitesource
      script: sbt whitesourceCheckPolicies whitesourceUpdate

    - stage: check
      script: sbt headerCheck || { echo "[error] Missing license headers found. Please run 'headerCreate' and commit the updated code."; false; }
      name: "Copyright header check"
    - script: sbt scalafmtCheck || { echo "[error] Unformatted code found. Please run 'Test/compile' and commit the reformatted code."; false; }
      name: "Code style check"
    - script: sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please run 'scalafmtSbt' and commit the reformatted code."; false; }
      name: "Build code style check"
    #TODO: enable cross builds by adding '+' in front of the command. Now not all the modules are compilable with Scala 2.11
    - env: CMD="Test/compile"

    - stage: test
    - env:
        - PRE_CMD="docker-compose up -d couchbase"
        - CMD=couchbaseClient/test
    #TODO: enable core tests
    # - env:
    #    - PRE_CMD="docker-compose up -d couchbase"
    #    - CMD=core/test
    - env:
        - CMD=lagom-persistence-couchbase-core/test
    - env:
        - PRE_CMD="docker-compose up -d couchbase"
        - CMD=lagom-persistence-couchbase-javadsl/test
    - env:
        - PRE_CMD="docker-compose up -d couchbase"
        - CMD=lagom-persistence-couchbase-scaladsl/test

stages:
  # runs on master commits and PRs
  - name: check
    if: NOT tag =~ ^v

  # runs on main repo master commits and version-tagged commits
  - name: whitesource
    if: repo = akka/akka-persistence-couchbase AND ( ( branch = master AND type = push ) OR tag =~ ^v )

after_failure:
  - docker-compose logs
  - find . -name "*.log" -exec ./scripts/cat-log.sh {} \;

before_cache:
  - find $HOME/.ivy2/ -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt   -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # encrypt with: travis encrypt WHITESOURCE_PASSWORD=...
    - secure: "HZY00jZS2NeNQm4zXLHnHTCwcWuXkDw/rXX1SSFvleDTQh1Hj/zAkC3CiEl2zmA8+bV6Cu+dBrOeK0gjYgmYNjiPdNkq4J8w34in6ebxZJfRz4FriVAniZHDXU86VupHPI4MvfKpfyeyQyr16jrMwm+vDP3Piuqzt//1M6056iTSHf0x0rqcmH8a+jiBAgk71/PUCoFdfjtE++niVF0iMKI6WMIA7BBpEW9bCjJ6xoqFZCpPv4blPLbxJGLAwWIycK8m1Me7caeTDrQC9q3vTBlrNEuZSChcSxc/K6D8xexMGl36wNpovNegpU9QobFlbcNNuTgfdsthil1zETTRNkjVjUxhbNalfuwyJMyTN5DT6e7b0n1hbZZ/LW/22X4iCK4DZ6sEmLSjuw/jdspXtSo0acgQVXDBJ0tWkBDnhpjbxR83Q7TUoIQww2tByrZs9kcYM/A9Csukl/Te8B4ICeWIxwEHePzI54JBURF1rBVnOjxM1C0Efp+tlA28y93ywKJPiUCAen2DLNop+WJuYWGSiiKRpOy/Bqdf3vkgmekObGNSJZeUYaW/nXZOF3a1RIc050L0VboJR+emDj+HP7KHK1h8zpezFmH9kIJ/Y4SX4Zq1sVtJGwrmzpsmorBEZQIRjON46469dQMu/P9VdUwGuT/E1LcBJyhO7/7ssPQ="
