version: '2'
services:
  ap-couchbase-master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8091-8094:8091-8094"
    - 11210:11210
    environment:
    - TYPE=MASTER
    - BUCKET=akka
  ap-couchbase-replica-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - TYPE=WORKER
    - BUCKET=akka
    - COUCHBASE_MASTER=ap-couchbase-master
    ports:
    - "8191-8194:8091-8094"
    - 11211:11210
  ap-couchbase-replica-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - TYPE=WORKER
    - BUCKET=akka
    - COUCHBASE_MASTER=ap-couchbase-master
    ports:
    - "8291-8294:8091-8094"
    - 11212:11210
